"""add Task tabel

Revision ID: 5606bcf493bb
Revises: d2ffbc7bdb62
Create Date: 2026-02-05 09:58:02.567187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5606bcf493bb'
down_revision: Union[str, Sequence[str], None] = 'd2ffbc7bdb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
